steps:
- checkout: self
  fetchDepth: 5

- script: |
   git fetch -q origin $(System.PullRequest.TargetBranch)
   if ! git diff --name-only HEAD $(git merge-base HEAD FETCH_HEAD) | grep -qvE '(\.rst$|^Doc|^Misc)'
   then
     echo "Only docs were updated"
     echo "##vso[task.setvariable variable=DocOnly,isOutput=true]true"
   fi
   if ! git diff --name-only HEAD $(git merge-base HEAD FETCH_HEAD) | grep -qE '(\.rst$|^Doc|^Misc)'
   then
     echo "No docs were updated"
     echo "##vso[task.setvariable variable=NoDocs,isOutput=true]true"
     exit
   fi
   echo "##vso[task.setvariable variable=DocOnly,isOutput=true]true"
  displayName: Detect doc changes
  condition: and(succeeded(), variables['System.PullRequest.TargetBranch'])
