name: build_windows

on:
  push:
    branches:
    - master
    - 3.8
    - 3.7
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7

jobs:
  build_win32:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: Build CPython
      run: PCbuild\build.bat -e -p Win32
    - name: Display build info
      run: python.bat -m test.pythoninfo
    - name: Tests
      run: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0

  build_win_amd64:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: Build CPython
      run: PCbuild\build.bat -e -p x64
    - name: Display build info
      run: python.bat -m test.pythoninfo
    - name: Tests
      run: PCbuild\rt.bat -x64 -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0
