name: build_windows

on:
  push:
    branches:
    - master
    - 3.8
    - 3.7
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7

jobs:
  build_windows:
    runs-on: windows-2019
    
    strategy:
      matrix:
        platform: [Win32, x64]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build CPython
      run: PCbuild\build.bat -e -p ${{ matrix.platform }}
    - name: Display build info
      run: python.bat -m test.pythoninfo
    - name: Tests
      run: PCbuild\rt.bat -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0
