name: patchcheck

on:
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7

jobs:
  patchcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
        depth: 1
    - name: Patchcheck
      run: SRCDIR=$(pwd) python3 Tools/scripts/patchcheck.py --is-pr true
