name: Checks

on:
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7

jobs:
  patchcheck:
    name: 'Whitespace Checks'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Patchcheck
      run: SRCDIR=$(pwd) python3 Tools/scripts/patchcheck.py --base-branch ${{github.base_ref}}
